apiVersion: apps/v1
kind: Deployment
metadata:
  name: cg-kube-dashboard
  labels:
    app: cg-kube-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cg-kube-dashboard
  template:
    metadata:
      labels:
        app: cg-kube-dashboard
    spec:
      containers:
        - name: cg-kube-dashboard
          image: cadugrillo/cg-kube-dashboard:1.0
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cg-kube-dashboard-service
spec:
  selector:
    app: cg-kube-dashboard
  ports:
    - port: 80
      targetPort: 80